# Generated by Django 5.1.1 on 2024-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_education_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("technologies", models.CharField(max_length=200)),
                ("git_url", models.URLField(blank=True)),
            ],
        ),
    ]
