# Generated by Django 5.1.1 on 2024-11-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("bio", models.TextField()),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                (
                    "email",
                    models.EmailField(
                        default="korutla.a@northeastern.edu", max_length=254
                    ),
                ),
                ("phone", models.CharField(default="+1 (207) 210-9705", max_length=20)),
                (
                    "location",
                    models.CharField(default="Boston, MA, USA", max_length=100),
                ),
            ],
        ),
    ]
